### ISSUE TITLE
Python programming and scientific computing

### ISSUE THREAD

**Issue by YipengHu** [YipengHu/MPHY0030#2]
@s-sd
I have migrated the mphy0030 repo here and please have a look, and palce any codes/tutorials you need in the ./tutorials, some of the previous ones may be moved to the legacy folder. please move them out and update as you see fit.

**Comment by s-sd** [comment]
@YipengHu Thank you! Need to add some images for a tutorial, nearly ~60MB, would that be okay? Or would you prefer that I add images to OneDrive and the rest of the code etc. here?

**Comment by YipengHu** [comment]
a link to large images sounds better to me

**Comment by s-sd** [comment]
I'll make a separate OneDrive link for the data files then and will add the solved code etc. after the lectures

**Comment by YipengHu** [comment]
close for now. use a new one if needed again.
